### ISSUE TITLE
Order of yamls matter

### ISSUE THREAD

**Issue by kv-sc** [syntacore/snippy#10]
Prepare YAML configs:

1.yaml

```
include:
    - 2.yaml
histogram:
    - [ADD, 1.0]
```

2.yaml

```
sections:
  - no:        0
    VMA:       0x10000
    SIZE:      0x20000
    LMA:       0x10000
    ACCESS:    r
  - no:        1
    VMA:       0x40000
    SIZE:      0x40000
    LMA:       0x40000
    ACCESS:    rx
  - no:        2
    VMA:       0x800000
    SIZE:      0x400000
    LMA:       0x800000
    ACCESS:    rw
```

3.yaml

```
access-ranges:
  - start: 0x800000
    size: 0x10000
    stride: 16
    first-offset: 0
    last-offset: 0
```

Now try following command lines:

```
$ ./llvm-snippy -march=riscv64-linux-gnu -num-instrs=10 -model-plugin=None 1.yaml 3.yaml
```

```
$ ./llvm-snippy -march=riscv64-linux-gnu -num-instrs=10 -model-plugin=None 3.yaml 1.yaml
1.yaml:1:1: warning: unknown key 'include'
include:
^~~~~~~
error: LLVM ERROR: Incorrect list of sections: list is empty
```

This error is really annoying.
