### ISSUE TITLE
RISC-V is not default architecture by default

### ISSUE THREAD

**Issue by cesarus777** [syntacore/snippy#18]
Reproduced on 1.0

I can't understand why default architecture is host even if it isn't supported. Can you please implement that default architecture is host if host architecture is supported, otherwise it's one of supported architecture?

Reproduction:

layout.yaml:
```yaml
sections:
  - name: text
    VMA: 0x1000
    LMA: 0x1000
    SIZE: 0x1000
    ACCESS: rx
  - name: data
    VMA: 0x2000
    LMA: 0x2000
    SIZE: 0x1000
    ACCESS: rw

histogram:
  - [ADD, 1]
```
Command:
```sh
llvm-snippy layout.yaml
```
Output:
```
'+relax' is not a recognized feature for this target (ignoring feature)
no snippy target for x86_64-unknown-linux-gnu
LLVM ERROR: sorry, target is not implemented
```
