### ISSUE TITLE
General purpose RW section is required even when no memory instructions were specified

### ISSUE THREAD

**Issue by cesarus777** [syntacore/snippy#19]
Reproduced on 1.0

layout.yaml:
```yaml
options:
  march: riscv64

sections:
  - name: text
    VMA: 0x1000
    LMA: 0x1000
    SIZE: 0x1000
    ACCESS: rx

histogram:
  - [ADD, 1]
```
Command:
```sh
llvm-snippy layout.yaml
```
Output:
```
error: LLVM ERROR: Incorrect list of sections: there are no general purpose RW sections
```
