### ISSUE TITLE
Use external stack if `stack` section wasn't specified

### ISSUE THREAD

**Issue by cesarus777** [syntacore/snippy#21]
Reproduced on 1.0

I want just to generate a simple snippet and link it with a simple wrapper. To do this I created config file:
```yaml
options:
  march: riscv64
  model-plugin: None
  seed: 0
  honor-target-abi: on

sections:
  - name: text
    VMA: 0x1000
    LMA: 0x1000
    SIZE: 0x1000
    ACCESS: rx
  - name: data
    VMA: 0x2000
    LMA: 0x2000
    SIZE: 0x1000
    ACCESS: rw

histogram:
  - [ADD, 1]
```
and called snippy:
```sh
llvm-snippy layout.yaml
```
Output:
```
error: LLVM ERROR: Cannot spill requested registers: no stack space allocated.
```

Expected behavior: use external stack if no stack section were specified.
