### ISSUE TITLE
`--dump-initial-registers-yaml` option doesn't work

### ISSUE THREAD

**Issue by cesarus777** [syntacore/snippy#22]
Reproduced on 1.0

layout.yaml:
```yaml
options:
  march: riscv64
  model-plugin: None
  seed: 0
  dump-initial-registers-yaml: regs.yaml

sections:
  - name: text
    VMA: 0x1000
    LMA: 0x1000
    SIZE: 0x1000
    ACCESS: rx
  - name: data
    VMA: 0x2000
    LMA: 0x2000
    SIZE: 0x1000
    ACCESS: rw

histogram:
  - [ADD, 1]
```
Command:
```sh
llvm-snippy layout.yaml
```
Output:
```
ld.lld: warning: cannot find entry symbol _start; not setting start address
warning: Skipping snippet execution on the model: model was set no 'None'.
remark: Snippet generator generated relocatable image: please, use linker with provided script to generate final image
_______
  Test Generation resulted in the following warnings:
    * Skipping snippet execution on the model: model was set no 'None'. (x1)
❯ ls -a
.  ..  layout.yaml  layout.yaml.elf  layout.yaml.ld
```
`regs.yaml` file wasn't generated.
